### ISSUE TITLE
Sample app breaks when running on IPv6

### ISSUE THREAD

**Issue by johnlim** [auth0-samples/auth0-express-webapp-sample#42]
Hi,

Running the sample app in /01-Login on the following set-up results in the error below when I click login in the webapp:
node version: v18.5.0
OS: macOS Monterey V12.4

```
const err = new AggregateError(errors);
AggregateError: Issuer.discover() failed.
    RequestError: Timeout awaiting 'request' for 5000ms
    RequestError: Timeout awaiting 'request' for 5000ms
    at Function.discover (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/openid-client/lib/issuer.js:265:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pReflect (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/p-reflect/index.js:5:17)
    at async Promise.all (index 0)
    at async /Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/p-memoize/index.js:33:22
    at async get (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/express-openid-connect/lib/client.js:43:18)
    at async pReflect (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/p-reflect/index.js:5:17)
    at async Promise.all (index 0)
    at async get (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/p-memoize/index.js:33:22)
    at async ResponseContext.login (/Users/xxx/git/auth0-express-webapp-sample/01-Login/node_modules/express-openid-connect/lib/context.js:182:20)
```
  
 
Disabling IPv6 on my mac as per [this article](https://support.blindsidenetworks.com/hc/en-us/articles/360050168052-How-to-disable-IPV6) resolves this. Is there a fix for this else, at least a warning for new users?

**Comment by adamjmcgrath** [comment]
Hi @johnlim - what was the advice that led you to try Disabling IPv6 on your Mac? 

This SDK is doing nothing special wrt making requests, so as long as any Node application can make requests to the internet on your machine, this SDK should be able to as well.

**Comment by johnlim** [comment]
Hi @adamjmcgrath, it took me a long time to debug and down many paths but this https://github.com/nodejs/node/issues/40537 prob is what finally led me down the path to disable IPv6.

**Comment by adamjmcgrath** [comment]
@johnlim - sorry for not getting back to this sooner. I don't think there's much to do for the SDK here, so closing. Feel free to ping me if you want to reopen
